### ISSUE TITLE
Cannot change wifi networks

### ISSUE THREAD

**Issue by topshed** [bjpirt/mirobot-ui#20]
I have not been able to get my Mirobot to change wifi networks. I was able to configure it to use my home wifi network from the default settings but now I cannot get it to change to another network. When I click on the 'scan' button, the window goes blank and never returns anything. UI version: 20141114131 Firmware version: 20141031

**Comment by bjpirt** [comment]
Did you upgrade the UI? It might not have fully flashed.

**Comment by topshed** [comment]
How can I tell? And if this is the problem, what can I do about it? Sent from Yahoo Mail for iPadAt 27 Jan 2015 09:33:12, Ben Pirt wrote:Did you upgrade the UI? It might not have fully flashed.

**Comment by bjpirt** [comment]
I mean did you attempt to upgrade the UI? Using the updater app. It's difficult to tell, but if you have attempted to upgrade then it might be worth trying to do it again manually.

To do this you can download the latest mirobot.bin file from https://github.com/bjpirt/mirobot-ui/releases and then visit http://10.10.100.254/iweb.html and select it in the second part of the form there. This seems to work best on Win IE if you have access to that. Otherwise, if you're on a mac there are instructions to do the same from the command line here: https://github.com/bjpirt/mirobot-ui

If it's OK, please could you continue this over on the Google Groups as it's a better place for this kind of support and generally gets a faster response as well as hitting a wider group of developers. It's also more searchable if others have the same problem.
Cheers!
